"""Minimal Numba CUDA stubs for spectralmc."""

from __future__ import annotations
from typing import Any, Callable, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

def jit(*args: Any, **kwargs: Any) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
def stream() -> "Stream": ...
def as_cuda_array(x: Any) -> Any: ...
def grid(ndim: int) -> int: ...

class Stream:
    def synchronize(self) -> None: ...
