from __future__ import annotations
from typing import Any

class Stream:
    def __init__(
        self, device: Any | None = ..., priority: int | None = ...
    ) -> None: ...
    def synchronize(self) -> None: ...
    def __enter__(self) -> "Stream": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: Any,
    ) -> None: ...

def empty_cache() -> None: ...
