"""
Type stubs for auto-generated protobuf modules.

These modules are generated by protoc and contain untyped Python code.
Using Any is acceptable here as this is external generated code.

This stub file is located in stubs/ (not src/) per coding_standards.md
exception for auto-generated protobuf code.

Generated protobuf modules from /opt/spectralmc_proto/
"""

from typing import Any

# Auto-generated protobuf modules (untyped)
common_pb2: Any
tensors_pb2: Any
simulation_pb2: Any
training_pb2: Any
models_pb2: Any

__all__ = [
    "common_pb2",
    "tensors_pb2",
    "simulation_pb2",
    "training_pb2",
    "models_pb2",
]
