"""
Type stubs for auto-generated protobuf modules.

These modules are generated by protoc and contain untyped Python code.
This stub provides minimal type information for mypy.

Generated protobuf modules from /opt/spectralmc_proto/
"""

from . import common_pb2, tensors_pb2, simulation_pb2, training_pb2, models_pb2

__all__ = [
    "common_pb2",
    "tensors_pb2",
    "simulation_pb2",
    "training_pb2",
    "models_pb2",
]
