from __future__ import annotations

# Enum values for dtype
DTYPE_FLOAT32: int = ...
DTYPE_FLOAT64: int = ...
DTYPE_COMPLEX64: int = ...
DTYPE_COMPLEX128: int = ...
DTYPE_FLOAT16: int = ...
DTYPE_BFLOAT16: int = ...

# Enum values for precision
PRECISION_FLOAT32: int = ...
PRECISION_FLOAT64: int = ...

# Enum values for device
DEVICE_CPU: int = ...
DEVICE_CUDA: int = ...
