from __future__ import annotations
from typing import Optional

ACTIVATION_KIND_MOD_RELU: int = ...
ACTIVATION_KIND_Z_RELU: int = ...

class PreserveWidthProto:
    def __init__(self) -> None: ...
    def CopyFrom(self, other: PreserveWidthProto) -> None: ...

class ExplicitWidthProto:
    value: int
    def __init__(self) -> None: ...
    def CopyFrom(self, other: ExplicitWidthProto) -> None: ...

class WidthSpecProto:
    preserve: PreserveWidthProto
    explicit: ExplicitWidthProto
    def __init__(self) -> None: ...
    def CopyFrom(self, other: WidthSpecProto | PreserveWidthProto | ExplicitWidthProto) -> None: ...
    def WhichOneof(self, name: str) -> Optional[str]: ...

class ActivationCfgProto:
    kind: int
    bias: float
    def __init__(self) -> None: ...
    def CopyFrom(self, other: ActivationCfgProto) -> None: ...

class LinearCfgProto:
    width: WidthSpecProto
    bias: float
    activation: ActivationCfgProto
    def __init__(self) -> None: ...
    def CopyFrom(self, other: LinearCfgProto | WidthSpecProto | ActivationCfgProto) -> None: ...
    def HasField(self, name: str) -> bool: ...

class CVNNConfigProto:
    dtype: int
    seed: int
    def __init__(self) -> None: ...
