# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# ruff: noqa
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63ommon.proto\x12\x10spectralmc.proto"\x9b\x01\n\x11ModelVersionProto\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\r\x12\x18\n\x10semantic_version\x18\x02 \x01(\t\x12\x13\n\x0bparent_hash\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_hash\x18\x04 \x01(\t\x12\x18\n\x10\x63ommit_timestamp\x18\x05 \x01(\t\x12\x16\n\x0e\x63ommit_message\x18\x06 \x01(\t"}\n\rTorchEnvProto\x12\x16\n\x0epython_version\x18\x01 \x01(\t\x12\x15\n\rtorch_version\x18\x02 \x01(\t\x12\x14\n\x0c\x63uda_version\x18\x03 \x01(\t\x12\x15\n\rcudnn_enabled\x18\x04 \x01(\x08\x12\x10\n\x08platform\x18\x05 \x01(\t"o\n\x1c\x41rchitectureFingerprintProto\x12\x1b\n\x13\x63vnn_structure_hash\x18\x01 \x01(\t\x12\x18\n\x10total_parameters\x18\x02 \x01(\r\x12\x18\n\x10\x61\x63tivation_kinds\x18\x03 \x01(\t*Y\n\x0ePrecisionProto\x12\x19\n\x15PRECISION_UNSPECIFIED\x10\x00\x12\x15\n\x11PRECISION_FLOAT32\x10\x01\x12\x15\n\x11PRECISION_FLOAT64\x10\x02*F\n\x0b\x44\x65viceProto\x12\x16\n\x12\x44\x45VICE_UNSPECIFIED\x10\x00\x12\x0e\n\nDEVICE_CPU\x10\x01\x12\x0f\n\x0b\x44\x45VICE_CUDA\x10\x02*\x9b\x01\n\nDTypeProto\x12\x15\n\x11\x44TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rDTYPE_FLOAT32\x10\x01\x12\x11\n\rDTYPE_FLOAT64\x10\x02\x12\x11\n\rDTYPE_FLOAT16\x10\x03\x12\x12\n\x0e\x44TYPE_BFLOAT16\x10\x04\x12\x13\n\x0f\x44TYPE_COMPLEX64\x10\x05\x12\x14\n\x10\x44TYPE_COMPLEX128\x10\x06\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PRECISIONPROTO._serialized_start = 432
    _PRECISIONPROTO._serialized_end = 521
    _DEVICEPROTO._serialized_start = 523
    _DEVICEPROTO._serialized_end = 593
    _DTYPEPROTO._serialized_start = 596
    _DTYPEPROTO._serialized_end = 751
    _MODELVERSIONPROTO._serialized_start = 35
    _MODELVERSIONPROTO._serialized_end = 190
    _TORCHENVPROTO._serialized_start = 192
    _TORCHENVPROTO._serialized_end = 317
    _ARCHITECTUREFINGERPRINTPROTO._serialized_start = 319
    _ARCHITECTUREFINGERPRINTPROTO._serialized_end = 430
# @@protoc_insertion_point(module_scope)
