# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# ruff: noqa
# source: simulation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10simulation.proto\x12\x10spectralmc.proto\x1a\x0c\x63ommon.proto"\xdc\x01\n\x15SimulationParamsProto\x12\x0c\n\x04skip\x18\x01 \x01(\r\x12\x11\n\ttimesteps\x18\x02 \x01(\r\x12\x14\n\x0cnetwork_size\x18\x03 \x01(\r\x12\x1a\n\x12\x62\x61tches_per_mc_run\x18\x04 \x01(\r\x12\x19\n\x11threads_per_block\x18\x05 \x01(\r\x12\x0f\n\x07mc_seed\x18\x06 \x01(\r\x12\x13\n\x0b\x62uffer_size\x18\x07 \x01(\r\x12/\n\x05\x64type\x18\x08 \x01(\x0e\x32 .spectralmc.proto.PrecisionProto"\x8f\x01\n\x17\x42lackScholesConfigProto\x12;\n\nsim_params\x18\x01 \x01(\x0b\x32\'.spectralmc.proto.SimulationParamsProto\x12\x1b\n\x13simulate_log_return\x18\x02 \x01(\x08\x12\x1a\n\x12normalize_forwards\x18\x03 \x01(\x08"X\n\x13OptionContractProto\x12\n\n\x02X0\x18\x01 \x01(\x01\x12\t\n\x01K\x18\x02 \x01(\x01\x12\t\n\x01T\x18\x03 \x01(\x01\x12\t\n\x01r\x18\x04 \x01(\x01\x12\t\n\x01\x64\x18\x05 \x01(\x01\x12\t\n\x01v\x18\x06 \x01(\x01"p\n\x13PricingResultsProto\x12\x12\n\ncall_price\x18\x01 \x01(\x01\x12\x11\n\tput_price\x18\x02 \x01(\x01\x12\x12\n\nunderlying\x18\x03 \x01(\x01\x12\x0f\n\x07\x66orward\x18\x04 \x01(\x01\x12\r\n\x05gamma\x18\x05 \x01(\x01".\n\x0e\x42oundSpecProto\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01"\xd8\x01\n\x10SobolConfigProto\x12\x12\n\ndimensions\x18\x01 \x01(\r\x12\x0c\n\x04seed\x18\x02 \x01(\r\x12K\n\rdomain_bounds\x18\x03 \x03(\x0b\x32\x34.spectralmc.proto.SobolConfigProto.DomainBoundsEntry\x1aU\n\x11\x44omainBoundsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .spectralmc.proto.BoundSpecProto:\x02\x38\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "simulation_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SOBOLCONFIGPROTO_DOMAINBOUNDSENTRY._options = None
    _SOBOLCONFIGPROTO_DOMAINBOUNDSENTRY._serialized_options = b"8\001"
    _SIMULATIONPARAMSPROTO._serialized_start = 53
    _SIMULATIONPARAMSPROTO._serialized_end = 273
    _BLACKSCHOLESCONFIGPROTO._serialized_start = 276
    _BLACKSCHOLESCONFIGPROTO._serialized_end = 419
    _OPTIONCONTRACTPROTO._serialized_start = 421
    _OPTIONCONTRACTPROTO._serialized_end = 509
    _PRICINGRESULTSPROTO._serialized_start = 511
    _PRICINGRESULTSPROTO._serialized_end = 623
    _BOUNDSPECPROTO._serialized_start = 625
    _BOUNDSPECPROTO._serialized_end = 671
    _SOBOLCONFIGPROTO._serialized_start = 674
    _SOBOLCONFIGPROTO._serialized_end = 890
    _SOBOLCONFIGPROTO_DOMAINBOUNDSENTRY._serialized_start = 805
    _SOBOLCONFIGPROTO_DOMAINBOUNDSENTRY._serialized_end = 890
# @@protoc_insertion_point(module_scope)
