# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import simulation_pb2 as simulation__pb2
from . import tensors_pb2 as tensors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0etraining.proto\x12\x10spectralmc.proto\x1a\x10simulation.proto\x1a\rtensors.proto"U\n\x13TrainingConfigProto\x12\x13\n\x0bnum_batches\x18\x01 \x01(\r\x12\x12\n\nbatch_size\x18\x02 \x01(\r\x12\x15\n\rlearning_rate\x18\x03 \x01(\x01"s\n\x10StepMetricsProto\x12\x0c\n\x04step\x18\x01 \x01(\x04\x12\x0c\n\x04loss\x18\x02 \x01(\x01\x12\x15\n\rgradient_norm\x18\x03 \x01(\x01\x12\x15\n\rlearning_rate\x18\x04 \x01(\x01\x12\x15\n\rbatch_time_ms\x18\x05 \x01(\x01"\xc9\x02\n\x18GbmCVNNPricerConfigProto\x12\x36\n\x03\x63\x66g\x18\x01 \x01(\x0b\x32).spectralmc.proto.BlackScholesConfigProto\x12\x39\n\rdomain_bounds\x18\x02 \x01(\x0b\x32".spectralmc.proto.SobolConfigProto\x12:\n\ncheckpoint\x18\x03 \x01(\x0b\x32&.spectralmc.proto.ModelCheckpointProto\x12\x42\n\x0foptimizer_state\x18\x04 \x01(\x0b\x32).spectralmc.proto.AdamOptimizerStateProto\x12\x1b\n\x13torch_cpu_rng_state\x18\x05 \x01(\x0c\x12\x1d\n\x15torch_cuda_rng_states\x18\x06 \x03(\x0c\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "training_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _TRAININGCONFIGPROTO._serialized_start = 69
    _TRAININGCONFIGPROTO._serialized_end = 154
    _STEPMETRICSPROTO._serialized_start = 156
    _STEPMETRICSPROTO._serialized_end = 271
    _GBMCVNNPRICERCONFIGPROTO._serialized_start = 274
    _GBMCVNNPRICERCONFIGPROTO._serialized_end = 603
# @@protoc_insertion_point(module_scope)
